/**
 * @fileoverview Auto-generated JSDoc typedefs from GraphQL schema.
 * Generated by: rake jsdoc:generate
 * Do NOT edit manually — re-run the Rake task to regenerate after schema changes.
 *
 * Usage: Import this file in any admin module to get IDE autocompletion.
 *   // @ts-check
 *   /// <reference path="../../jsdoc/types.js" />
 *
 * @module types
 */

/**
 * @typedef {Object} WpPost
 * @property {string|number} ID
 * @property {string} post_title
 * @property {string} post_content
 * @property {string} post_excerpt
 * @property {string} post_status - "publish" | "draft" | "pending" | "private" | "trash"
 * @property {string} post_date - ISO8601 datetime string
 * @property {string} post_modified - ISO8601 datetime string
 * @property {string} post_name - URL slug
 * @property {string} post_type - "post" | "page" | "attachment"
 * @property {WpUser|null} author
 * @property {Array<WpTermTaxonomy>} [categories]
 * @property {Array<WpTermTaxonomy>} [tags]
 */

/**
 * @typedef {Object} WpUser
 * @property {string|number} ID
 * @property {string} user_login
 * @property {string} user_email
 * @property {string} user_url
 * @property {string} display_name
 * @property {string} user_registered - ISO8601 datetime string
 * @property {string} role - "administrator" | "editor" | "author" | "contributor" | "subscriber"
 * @property {Array<WpPost>} [posts]
 */

/**
 * @typedef {Object} WpPage
 * @property {string|number} ID
 * @property {string} post_title
 * @property {string} post_content
 * @property {string} post_excerpt
 * @property {string} post_status - "publish" | "draft" | "pending" | "private" | "trash"
 * @property {string} post_name - URL slug
 * @property {number} post_parent - ID of parent page (0 if top-level)
 * @property {number} menu_order
 * @property {string} post_date - ISO8601 datetime string
 * @property {WpUser|null} author
 */

/**
 * @typedef {Object} WpTermTaxonomy
 * @property {string|number} term_taxonomy_id
 * @property {string} taxonomy - "category" | "post_tag"
 * @property {string} description
 * @property {number} count
 * @property {string} name
 * @property {string} slug
 */

/**
 * GraphQL query result wrapper for adminPosts
 * @typedef {Object} AdminPostsResult
 * @property {Array<WpPost>} adminPosts
 */

/**
 * GraphQL query result wrapper for pages
 * @typedef {Object} PagesResult
 * @property {Array<WpPage>} pages
 */

/**
 * GraphQL query result wrapper for users
 * @typedef {Object} UsersResult
 * @property {Array<WpUser>} users
 */

/**
 * GraphQL mutation result for post operations
 * @typedef {Object} PostMutationResult
 * @property {WpPost|null} post
 * @property {Array<string>} errors
 */

/**
 * GraphQL mutation result for page operations
 * @typedef {Object} PageMutationResult
 * @property {WpPage|null} page
 * @property {Array<string>} errors
 */

/**
 * GraphQL mutation result for delete operations
 * @typedef {Object} DeleteMutationResult
 * @property {boolean} success
 * @property {Array<string>} errors
 */

/**
 * GraphQL mutation result for user role update
 * @typedef {Object} UpdateUserRoleResult
 * @property {WpUser|null} user
 * @property {Array<string>} errors
 */
