namespace :jsdoc do
  desc "Generate JSDoc typedefs from GraphQL schema and write to frontWP/jsdoc/types.js"
  task generate: :environment do
    generator = JsdocGenerator.new(AppSchema)
    output_path = ENV.fetch("JSDOC_OUTPUT", Rails.root.join("../../frontWP/jsdoc/types.js").to_s)
    FileUtils.mkdir_p(File.dirname(output_path))
    File.write(output_path, generator.generate)
    puts "Generated #{output_path}"
  end
end

class JsdocGenerator
  # GraphQL scalar -> JSDoc type mapping
  SCALAR_MAP = {
    "String"           => "string",
    "Boolean"          => "boolean",
    "Int"              => "number",
    "Float"            => "number",
    "ID"               => "string|number",
    "ISO8601DateTime"  => "string"
  }.freeze

  # Only generate typedefs for these core domain types
  DOMAIN_TYPES = %w[
    WpPostType WpUserType WpPageType WpTermTaxonomyType
  ].freeze

  def initialize(schema)
    @schema = schema
  end

  def generate
    lines = []
    lines << file_header
    DOMAIN_TYPES.each do |type_name|
      gql_type = @schema.types[type_name]
      next unless gql_type&.respond_to?(:fields)
      lines << typedef_for(gql_type)
    end
    lines.join("\n")
  end

  private

  def file_header
    <<~JS
      /**
       * @fileoverview Auto-generated JSDoc typedefs from GraphQL schema.
       * Generated by: rake jsdoc:generate
       * Do NOT edit manually — re-run the Rake task to regenerate after schema changes.
       *
       * @module types
       */
    JS
  end

  def typedef_for(gql_type)
    name = ruby_to_js_name(gql_type.graphql_name)
    props = gql_type.fields.map do |field_name, field|
      js_type = gql_type_to_jsdoc(field.type)
      " * @property {#{js_type}} #{field_name}"
    end

    [
      "",
      "/**",
      " * @typedef {Object} #{name}",
      *props,
      " */",
      ""
    ].join("\n")
  end

  def gql_type_to_jsdoc(type)
    unwrapped = unwrap_non_null(type)

    if unwrapped.is_a?(GraphQL::Schema::List)
      inner = gql_type_to_jsdoc(unwrapped.of_type)
      "Array<#{inner}>"
    elsif unwrapped.respond_to?(:fields)
      # Object type — reference by name
      ruby_to_js_name(unwrapped.graphql_name)
    else
      SCALAR_MAP[unwrapped.graphql_name] || "any"
    end
  end

  def unwrap_non_null(type)
    type.is_a?(GraphQL::Schema::NonNull) ? type.of_type : type
  end

  def ruby_to_js_name(graphql_name)
    # WpPostType -> WpPost, WpUserType -> WpUser, etc.
    graphql_name.sub(/Type$/, "")
  end
end
